version = 0.1

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todolist-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fnxysdhusbno"
region = "us-east-1"
